#!/usr/bin/env node
// Generates src/generated/opsRegistry.ts from dist/chef/operations
const fs = require("fs");
const path = require("path");

const EXCLUDED = new Set(["Argon2", "Argon2Compare", "Bzip2Compress", "Bzip2Decompress", "CSSSelector"]);

const opDir = path.resolve(__dirname, "../dist/chef/operations");
if (!fs.existsSync(opDir)) {
    console.error("ERROR: dist/chef/operations not found — run 'npm run build:chef' first");
    process.exit(1);
}

const files = fs.readdirSync(opDir)
    .filter(f => f.endsWith(".js") && !f.endsWith(".map.js") && f !== "index.js");

const entries = [];
for (const file of files) {
    const opName = path.basename(file, ".js");
    if (EXCLUDED.has(opName)) continue;
    try {
        const mod = require(path.join(opDir, file));
        const Cls = mod[opName] || mod.default;
        if (!Cls || typeof Cls !== "function") continue;
        const instance = new Cls();
        if (!instance.name) continue;
        entries.push({
            opName,
            displayName: instance.name,
            moduleName: instance.module || "Default",
        });
    } catch {
        // skip ops that fail to instantiate (missing native deps etc.)
    }
}

entries.sort((a, b) => a.displayName.localeCompare(b.displayName));

const lines = [
    `// AUTO-GENERATED by scripts/generateOpsRegistry.js — do not edit by hand`,
    `import type { Operation } from "../chef/Operation";`,
    ``,
    `export interface OpMeta {`,
    `    opName: string;`,
    `    displayName: string;`,
    `    module: string;`,
    `    factory: () => Operation;`,
    `}`,
    ``,
    `const registry: OpMeta[] = [`,
];

for (const e of entries) {
    // Require path relative to src/generated/ → ../chef/operations/<opName>
    const requirePath = `../chef/operations/${e.opName}`;
    lines.push(
        `    { opName: ${JSON.stringify(e.opName)}, displayName: ${JSON.stringify(e.displayName)}, ` +
        `module: ${JSON.stringify(e.moduleName)}, ` +
        `factory: () => { const m = require(${JSON.stringify(requirePath)}); return new (m.${e.opName} || m.default)(); } },`
    );
}

lines.push(`];`);
lines.push(``);
lines.push(`export default registry;`);
lines.push(``);
lines.push(`export function findOp(displayName: string): OpMeta | undefined {`);
lines.push(`    return registry.find(e => e.displayName.toLowerCase() === displayName.toLowerCase());`);
lines.push(`}`);
lines.push(``);
lines.push(`export function allOps(): OpMeta[] { return registry; }`);
lines.push(``);

const outDir = path.resolve(__dirname, "../src/generated");
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "opsRegistry.ts"), lines.join("\n"));
console.log(`Generated ${entries.length} operations → src/generated/opsRegistry.ts`);
