import { Argon2Compare } from "../../src/chef/operations/Argon2Compare";

describe("Argon2Compare", () => {
    const op = new Argon2Compare();
    // Generated with: argon2.hash("password", {salt: Buffer.from("somesalt")})
    const VALID_HASH = "$argon2i$v=19$m=4096,t=3,p=1$c29tZXNhbHQ$fP8I+pW1vX6A7/N37vU0D3S7vI6+7N9I2G8P8I+pW1v"; // This might not be exact, I'll use a real one from a quick run if it fails, but for now I'll generate one in the test if I can, or just use a placeholder and see.
    
    // Actually, I can use the Argon2 operation to generate it if I want to be sure, but it's better to have a static one.
    // Let's use a known one.
    const hash = "$argon2i$v=19$m=4096,t=3,p=1$c29tZXNhbHQ$R56C19Y9OvM9O9O9O9O9O9O9O9O9O9O9O9O9O9O9O9O"; // Placeholder

    test("Match: Correct password", async () => {
        // I'll use a real hash generated by argon2 lib for "password" with salt "somesalt"
        // $argon2i$v=19$m=4096,t=3,p=1$c29tZXNhbHQ$mZp7Y57yI4y3v7L7v7L7v7L7v7L7v7L7v7L7v7L7v7I
        // Wait, I can just use the Argon2 operation to get a valid hash for testing.
        const argon2Op = new (require("../../src/chef/operations/Argon2").Argon2)();
        const generatedHash = await argon2Op.run("password", [{string: "somesalt", option: "UTF8"}, 3, 4096, 1, 32, "Argon2i", "Encoded hash"]);

        const result = await op.run("password", [generatedHash]);
        expect(result).toBe("Match: password");
    });

    test("No match: Incorrect password", async () => {
        const argon2Op = new (require("../../src/chef/operations/Argon2").Argon2)();
        const generatedHash = await argon2Op.run("password", [{string: "somesalt", option: "UTF8"}, 3, 4096, 1, 32, "Argon2i", "Encoded hash"]);

        const result = await op.run("wrongpassword", [generatedHash]);
        expect(result).toBe("No match");
    });

    test("No match: Invalid hash format", async () => {
        const result = await op.run("password", ["invalidhash"]);
        expect(result).toBe("No match");
    });
});
